require:
  - rubocop-minitest
  - rubocop-performance

AllCops:
  NewCops: disable
  TargetRubyVersion: 3.2
  Exclude:
    - "bin/**/*"
    - "sig/**/*"

Bundler/OrderedGems:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/EmptyLinesAroundAccessModifier:
  EnforcedStyle: only_before

Lint/SuppressedException:
  Exclude:
    - "test/**/*"

Metrics/BlockLength:
  Exclude:
    - "test/**/*"

Metrics/MethodLength:
  Max: 20
  Exclude:
    - "test/**/*"

Naming/PredicateName:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/GuardClause:
  Exclude:
    - lib/jiki_config/environment.rb

Style/NumericPredicate:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Naming/FileName:
  Exclude:
    - "lib/jiki-config.rb"

Naming/VariableNumber:
  EnforcedStyle: snake_case

Style/LambdaCall:
  EnforcedStyle: braces
